data:
  file_path: 'Scats-Data-October-2006-Bundoora.csv'
  lag: 12
  n_scats_options: ['all', 10, 5]

gui:
  window_size: '1400x800'

model:
  batch_size: 256
  epochs: 3
  validation_split: 0.05

training:
  models: ['lstm', 'gru', 'bilstm', 'cnnlstm', 'saes']
  model_save_path: 'main/model/trained'

evaluation:
  metric_save_path: 'reports/metric-comparison/'
  prediction_save_path: 'reports/prediction-comparison/'
  report-summary_save_path: 'reports/summary/'  

