# config.yml
data:
  file_path: 'Scats-Data-October-2006-Bundoora.csv'
  lag: 12
  n_scats_options: [5, 10, 'all']

model:
  batch_size: 256
  epochs: 3
  validation_split: 0.05

training:
  models: ['lstm', 'gru', 'bilstm', 'cnnlstm', 'saes']
  model_save_path: 'model/trained'

evaluation:
  image_save_path: 'model/evaluation'  

gui:
  window_size: '1400x800'